"""Initial migration.

Revision ID: 5d19f5db792a
Revises: 
Create Date: 2024-09-16 11:30:03.059987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d19f5db792a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Assuming 'user' table has a user with ID 1 (admin or default user)
    op.add_column('notebook', sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'notebook', 'user', ['user_id'], ['id'])
    op.alter_column('notebook', 'user_id', server_default=None)  # Remove the default after applying

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
